spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/transactions
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  error:
    include-message: always
    include-binding-errors: always

